name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with debug and open handles detection
        run: |
          echo "Starting tests..."
          npm test -- --detectOpenHandles
          echo "Tests completed."

      - name: Build Docker image
        run: docker build -t keyurpatil06/hello-world-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push keyurpatil06/hello-world-app

      - name: Deploy to localhost
        run: |
          docker pull keyurpatil06/hello-world-app
          docker stop hello-world-app-container || true
          docker rm hello-world-app-container || true
          docker run -d --name hello-world-app-container -p 3000:3000 keyurpatil06/hello-world-app
          echo "Waiting for container to start..."
          sleep 5
          docker ps
          docker logs hello-world-app-container

      - name: Verify successful deployment
        run: |
          echo "Checking service..."
          curl -f http://localhost:3000 || (docker logs hello-world-app-container && exit 1)
